# Generated by Django 3.0.2 on 2020-11-11 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0003_auto_20201109_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalappliances',
            name='duration',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
