# Generated by Django 3.0.2 on 2020-11-26 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0004_electricalappliances_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Windmills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('energy_character', models.FileField(upload_to='uploads/')),
                ('price_without_bashta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вартість ВЕУ (без башти)')),
                ('price_bashta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вартість башти')),
            ],
        ),
        migrations.AlterField(
            model_name='electricalappliances',
            name='duration',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тривалість роботи (хв)'),
        ),
        migrations.AlterField(
            model_name='electricalappliances',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='electricalappliances',
            name='power',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потужність (Вт)'),
        ),
        migrations.CreateModel(
            name='lengthLopati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Варіанти поставки ВЕУ з різними висотами башти')),
                ('windmills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laba.Windmills')),
            ],
        ),
    ]
