# Generated by Django 3.0.2 on 2020-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0005_auto_20201126_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windmills',
            name='energy_character',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
