# Generated by Django 3.0.2 on 2020-11-26 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0009_auto_20201126_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lengthlopati',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Ціна'),
        ),
    ]
