# Generated by Django 3.0.2 on 2020-11-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0010_auto_20201126_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lengthLopati',
            new_name='Tower',
        ),
    ]
