# Generated by Django 3.0.2 on 2020-11-27 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0012_auto_20201127_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Висота башти'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Вартість башти'),
        ),
        migrations.AlterField(
            model_name='windmills',
            name='energy_character',
            field=models.FileField(null=True, upload_to='energy_characteristic/', verbose_name='Енергетична характеристика ВЕУ'),
        ),
    ]
