# Generated by Django 3.0.2 on 2020-11-28 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0013_auto_20201127_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='windmills',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Який вітряк'),
        ),
    ]
