# Generated by Django 3.0.2 on 2020-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0015_towernew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='height',
            field=models.IntegerField(verbose_name='Висота башти'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='price',
            field=models.IntegerField(verbose_name='Вартість башти'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='windmills',
            field=models.IntegerField(verbose_name='Який вітряк'),
        ),
    ]
